あいさつアプリ課題完了
masawo9409/greeting pull request #1
Opened 2022-10-11 10:53 UTC by masawo9409

確認お願いいたします！

2022-10-11 21:18 UTC, kazu-taka requested changes
@masawo9409 
コメントしたので確認お願いします😊

2022-10-11 21:18 UTC, kazu-taka commented on app/Http/Controllers/greetApp.php
> +class greetApp extends Controller
@masawo9409 
コントローラの名前はアッパーキャメルケースになります！
今回のgreetAppだとロアーキャメルケースとなります✨
また、Appはアプリ的なイメージの言葉になるので、コントローラの場合はGreetだけで良いと思います！
今回はこのままでOKです👍

2022-10-11 21:18 UTC, kazu-taka commented on app/Http/Controllers/greetApp.php
> +        return view('message.randam',['msg'=>$randam]);
@masawo9409 
`=`の前後にスペースが入っていないので、フォーマッターを使用して修正お願いします！
また不要なコメントは削除お願いします🙏

2022-10-11 21:18 UTC, kazu-taka commented on app/Http/Controllers/greetApp.php
> +        return view('message.randam',['msg'=>$randam]);
@masawo9409 
array_randの第2引数は、デフォルトで1が設定されるので、省略してOKです✨
![image](https://user-images.githubusercontent.com/5278718/195199921-80168e85-4210-4f2c-9838-fd799275e7bb.png)

2022-10-13 05:58 UTC, masawo9409 commented on app/Http/Controllers/greetApp.php
> +class greetApp extends Controller
確認ありがとうございます。
承知いたしました！
今回は一旦このまま行きます。

2022-10-13 11:53 UTC, kazu-taka commented
@masawo9409 
マージしてOKです👍
![LGTM](https://image.lgtmoon.dev/151973)

2022-10-15 03:16 UTC, merged